name: Laravel CI/CD Pipeline

on:
  push:
    branches: [ main, dev, "feature/**" ]
  pull_request:
    branches: [ main, dev ]

jobs:
  # Tahap 1: Build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

  # Tahap 2: Test
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - name: Install Dependencies
        run: composer update -q --no-interaction --no-progress --prefer-dist --no-scripts
      - name: Prepare Laravel Environment
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Generate Key
        run: php artisan key:generate
      - name: Run Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test

  # Tahap 3: Staging
  staging:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Staging Deployment
        run: echo "Deploying to Staging Environment..."

  # Tahap 4: Production
  production:
    needs: staging
    # Hanya berjalan di branch main
    if: github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    # Memanggil environment 'production' yang sudah disetel Required Reviewer
    environment: production 
    steps:
      - name: Echo Deployment Steps
        run: |
          echo "Simulasi Deploy ke Production (deploy.sh):"
          echo "1. php artisan down"
          echo "2. git pull origin main"
          echo "3. composer install --no-interaction --prefer-dist --optimize-autoloader"
          echo "4. php artisan migrate --force"
          echo "5. php artisan optimize:clear"
          echo "6. npm run build"
          echo "7. php artisan up"